"""init

Revision ID: 2c38a5cd4d46
Revises: 
Create Date: 2023-03-25 08:54:34.786402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2c38a5cd4d46"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "filedata",
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("file_id", sa.Integer(), nullable=False),
        sa.Column("owner_id", sa.Integer(), nullable=True),
        sa.Column("filename", sa.String(), nullable=True),
        sa.Column("filepath", sa.String(), nullable=True),
        sa.Column("filebase64", sa.LargeBinary(), nullable=True),
        sa.PrimaryKeyConstraint("file_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("filedata")
    # ### end Alembic commands ###
